In [1]:
import pandas as pd

data = [
["Bangalore South","Karnataka","ABC","Ravi Kumar",45231,120000,"Male",45],
["Bangalore South","Karnataka","XYZ","Sneha Reddy",50321,120000,"Female",38],
["Bangalore South","Karnataka","PQR","Amit Shah",18448,120000,"Male",52],
["Mysore","Karnataka","ABC","Kiran Gowda",62341,150000,"Male",41],
["Mysore","Karnataka","XYZ","Divya Sharma",54321,150000,"Female",36],
["Mysore","Karnataka","PQR","Rahul Verma",33211,150000,"Male",48],
["Tumkur","Karnataka","ABC","Suresh Naik",41234,110000,"Male",50],
["Tumkur","Karnataka","XYZ","Anita Desai",45210,110000,"Female",39],
["Tumkur","Karnataka","PQR","Manoj Singh",23556,110000,"Male",44]
]

df = pd.DataFrame(data, columns=[
"Constituency","State","Party","Candidate","Votes","Total_Votes","Gender","Age"
])

df.head()

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age
0,Bangalore South,Karnataka,ABC,Ravi Kumar,45231,120000,Male,45
1,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38
2,Bangalore South,Karnataka,PQR,Amit Shah,18448,120000,Male,52
3,Mysore,Karnataka,ABC,Kiran Gowda,62341,150000,Male,41
4,Mysore,Karnataka,XYZ,Divya Sharma,54321,150000,Female,36

In [2]:
df.to_csv("election_data.csv", index=False)

In [3]:
from google.colab import files
files.download("election_data.csv")

In [4]:
# Check duplicate rows
duplicates = df.duplicated()

print("Number of duplicate rows:", duplicates.sum())

# Show duplicates if any
df[duplicates]

Number of duplicate rows: 0

Empty DataFrame
Columns: [Constituency, State, Party, Candidate, Votes, Total_Votes, Gender, Age]
Index: []

In [5]:
df = df.drop_duplicates()

In [6]:
df.dtypes

Constituency    object
State           object
Party           object
Candidate       object
Votes            int64
Total_Votes      int64
Gender          object
Age              int64
dtype: object

In [7]:
df["Votes"] = pd.to_numeric(df["Votes"], errors="coerce")
df["Total_Votes"] = pd.to_numeric(df["Total_Votes"], errors="coerce")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [8]:
df.dtypes

Constituency    object
State           object
Party           object
Candidate       object
Votes            int64
Total_Votes      int64
Gender          object
Age              int64
dtype: object

In [9]:
df.groupby("Constituency")["Total_Votes"].nunique()

Constituency
Bangalore South    1
Mysore             1
Tumkur             1
Name: Total_Votes, dtype: int64

In [10]:
df.groupby("Constituency")["Total_Votes"].nunique().reset_index()

      Constituency  Total_Votes
0  Bangalore South            1
1           Mysore            1
2           Tumkur            1

In [11]:
df["Vote %"] = (df["Votes"] / df["Total_Votes"]) * 100

In [12]:
df.head()

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age,Vote %
0,Bangalore South,Karnataka,ABC,Ravi Kumar,45231,120000,Male,45,37.692500
1,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38,41.934167
2,Bangalore South,Karnataka,PQR,Amit Shah,18448,120000,Male,52,15.373333
3,Mysore,Karnataka,ABC,Kiran Gowda,62341,150000,Male,41,41.560667
4,Mysore,Karnataka,XYZ,Divya Sharma,54321,150000,Female,36,36.214000

In [13]:
df["Vote %"] = df["Vote %"].round(2)

In [14]:
df[["Candidate", "Votes", "Total_Votes", "Vote %"]].head()

      Candidate  Votes  Total_Votes  Vote %
0    Ravi Kumar  45231       120000   37.69
1   Sneha Reddy  50321       120000   41.93
2     Amit Shah  18448       120000   15.37
3   Kiran Gowda  62341       150000   41.56
4  Divya Sharma  54321       150000   36.21

In [15]:
# Get index of max votes per constituency
idx = df.groupby("Constituency")["Votes"].idxmax()

# Extract winner rows
winners = df.loc[idx][["Constituency", "Candidate", "Party", "Votes"]]

winners

      Constituency    Candidate Party  Votes
1  Bangalore South  Sneha Reddy   XYZ  50321
3           Mysore  Kiran Gowda   ABC  62341
7           Tumkur  Anita Desai   XYZ  45210

In [16]:
df["Is_Winner"] = df.groupby("Constituency")["Votes"].transform("max") == df["Votes"]

df[df["Is_Winner"]][["Constituency", "Candidate", "Party", "Votes"]]

      Constituency    Candidate Party  Votes
1  Bangalore South  Sneha Reddy   XYZ  50321
3           Mysore  Kiran Gowda   ABC  62341
7           Tumkur  Anita Desai   XYZ  45210

In [17]:
pivot = df.pivot_table(
    index="Constituency",
    columns="Candidate",
    values="Votes",
    aggfunc="max"
)

pivot

Candidate,Amit Shah,Anita Desai,Divya Sharma,Kiran Gowda,Manoj Singh,Rahul Verma,Ravi Kumar,Sneha Reddy,Suresh Naik
Constituency,,,,,,,,,
Bangalore South,18448.0,NaN,NaN,NaN,NaN,NaN,45231.0,50321.0,NaN
Mysore,NaN,NaN,54321.0,62341.0,NaN,33211.0,NaN,NaN,NaN
Tumkur,NaN,45210.0,NaN,NaN,23556.0,NaN,NaN,NaN,41234.0

In [18]:
party_votes = df.groupby("Party")["Votes"].sum().reset_index()

party_votes = party_votes.sort_values(by="Votes", ascending=False)

party_votes

  Party   Votes
2   XYZ  149852
0   ABC  148806
1   PQR   75215

In [19]:
party_votes.iloc[0]

Party       XYZ
Votes    149852
Name: 2, dtype: object

In [20]:
idx = df.groupby("Constituency")["Votes"].idxmax()
winners = df.loc[idx]

In [21]:
party_wins = winners.groupby("Party")["Constituency"].count().reset_index()

party_wins = party_wins.sort_values(by="Constituency", ascending=False)

party_wins

  Party  Constituency
1   XYZ             2
0   ABC             1

In [22]:
party_wins.iloc[0]

Party           XYZ
Constituency      2
Name: 1, dtype: object

In [23]:
gender_votes = df.groupby("Gender")["Votes"].sum().reset_index()

gender_votes

   Gender   Votes
0  Female  149852
1    Male  224021

In [24]:
gender_votes = gender_votes.sort_values(by="Votes", ascending=False)
gender_votes

   Gender   Votes
1    Male  224021
0  Female  149852

In [25]:
total_votes = gender_votes["Votes"].sum()

gender_votes["Percentage"] = (gender_votes["Votes"] / total_votes) * 100
gender_votes

   Gender   Votes  Percentage
1    Male  224021    59.91901
0  Female  149852    40.08099

In [26]:
idx = df.groupby("Constituency")["Votes"].idxmax()
winners = df.loc[idx]

In [27]:
avg_age = winners["Age"].mean()
avg_age

np.float64(39.333333333333336)

In [28]:
round(avg_age, 2)

np.float64(39.33)

In [29]:
youngest = df.loc[df["Age"].idxmin()]
youngest

Constituency          Mysore
State              Karnataka
Party                    XYZ
Candidate       Divya Sharma
Votes                  54321
Total_Votes           150000
Gender                Female
Age                       36
Vote %                 36.21
Is_Winner              False
Name: 4, dtype: object

In [30]:
oldest = df.loc[df["Age"].idxmax()]
oldest

Constituency    Bangalore South
State                 Karnataka
Party                       PQR
Candidate             Amit Shah
Votes                     18448
Total_Votes              120000
Gender                     Male
Age                          52
Vote %                    15.37
Is_Winner                 False
Name: 2, dtype: object

In [31]:
youngest[["Candidate","Age","Constituency","Party"]]
oldest[["Candidate","Age","Constituency","Party"]]

Candidate             Amit Shah
Age                          52
Constituency    Bangalore South
Party                       PQR
Name: 2, dtype: object

In [32]:
df.to_csv("election_data.csv", index=False)
from google.colab import files
files.download("election_data.csv")

In [33]:
winners.to_csv("winners.csv", index=False)

from google.colab import files
files.download("winners.csv")

In [34]:
# Sort votes within each constituency
df_sorted = df.sort_values(["Constituency", "Votes"], ascending=[True, False])

# Get top 2 candidates per constituency
top2 = df_sorted.groupby("Constituency").head(2)

# Calculate margin
margin_df = top2.groupby("Constituency").agg({
    "Votes": lambda x: x.iloc[0] - x.iloc[1]
}).reset_index()

margin_df.rename(columns={"Votes": "Winning Margin"}, inplace=True)

margin_df

      Constituency  Winning Margin
0  Bangalore South            5090
1           Mysore            8020
2           Tumkur            3976

In [35]:
winners = winners.merge(margin_df, on="Constituency")
winners

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age,Vote %,Is_Winner,Winning Margin
0,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38,41.93,True,5090
1,Mysore,Karnataka,ABC,Kiran Gowda,62341,150000,Male,41,41.56,True,8020
2,Tumkur,Karnataka,XYZ,Anita Desai,45210,110000,Female,39,41.10,True,3976

In [36]:
# Sort votes descending within each constituency
df_sorted = df.sort_values(["Constituency", "Votes"], ascending=[True, False])

# Get top 2 candidates per constituency
top2 = df_sorted.groupby("Constituency").head(2)

# Calculate winning margin
margin_df = top2.groupby("Constituency").agg({
    "Votes": lambda x: x.iloc[0] - x.iloc[1]
}).reset_index()

margin_df.rename(columns={"Votes": "Winning Margin"}, inplace=True)

margin_df.head()

      Constituency  Winning Margin
0  Bangalore South            5090
1           Mysore            8020
2           Tumkur            3976

In [37]:
# Recreate winners if not present
idx = df.groupby("Constituency")["Votes"].idxmax()
winners = df.loc[idx]

# Merge margin
winners = winners.merge(margin_df, on="Constituency")

winners[["Constituency","Candidate","Party","Votes","Winning Margin"]]

      Constituency    Candidate Party  Votes  Winning Margin
0  Bangalore South  Sneha Reddy   XYZ  50321            5090
1           Mysore  Kiran Gowda   ABC  62341            8020
2           Tumkur  Anita Desai   XYZ  45210            3976

In [38]:
close_contests = winners[winners["Winning Margin"] < 5000]

close_contests[["Constituency","Candidate","Winning Margin"]]

  Constituency    Candidate  Winning Margin
2       Tumkur  Anita Desai            3976

In [39]:
df[df["Party"] == "XYZ"]

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age,Vote %,Is_Winner
1,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38,41.93,True
4,Mysore,Karnataka,XYZ,Divya Sharma,54321,150000,Female,36,36.21,False
7,Tumkur,Karnataka,XYZ,Anita Desai,45210,110000,Female,39,41.10,True

In [40]:
df[df["Gender"] == "Female"]

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age,Vote %,Is_Winner
1,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38,41.93,True
4,Mysore,Karnataka,XYZ,Divya Sharma,54321,150000,Female,36,36.21,False
7,Tumkur,Karnataka,XYZ,Anita Desai,45210,110000,Female,39,41.10,True

In [41]:
df[(df["Party"] == "XYZ") & (df["Gender"] == "Female")]

,Constituency,State,Party,Candidate,Votes,Total_Votes,Gender,Age,Vote %,Is_Winner
1,Bangalore South,Karnataka,XYZ,Sneha Reddy,50321,120000,Female,38,41.93,True
4,Mysore,Karnataka,XYZ,Divya Sharma,54321,150000,Female,36,36.21,False
7,Tumkur,Karnataka,XYZ,Anita Desai,45210,110000,Female,39,41.10,True

In [42]:
# See XYZ performance
xyz = df[df["Party"] == "XYZ"]

xyz.groupby("Constituency")["Votes"].sum().sort_values(ascending=False)

Constituency
Mysore             54321
Bangalore South    50321
Tumkur             45210
Name: Votes, dtype: int64